#!/usr/bin/env bash

./stop || true

echo "### Starting promat service docker ###"

promat_service_port=${PROMAT_SERVICE_PORT:-8080}
docker run --rm --name promat-service -d -e JAVA_MAX_HEAP_SIZE=2G -e PROMAT_DB_URL=${PROMAT_DB_URL} -p ${promat_service_port}:8080 $@ docker-io.dbc.dk/promat-service:devel

attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${promat_service_port}/openapi); do
    if [[ ${attempts} -eq ${max_attempts} ]]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for promat service ###"
curl -vs http://localhost:${promat_service_port}/openapi
echo ""
