query ManifestationByPid($pid: String!) {
    manifestation(pid: $pid) {
        pid
        shelfCreator { display }
        classifications { display dk5Heading }
        edition { edition publicationYear { year } }
        identifiers { type value }
        materialTypes {
            materialTypeGeneral { code display }
            materialTypeSpecific { code display } }
        physicalDescription { summaryFull }
        publisher
        placeOfPublication
        catalogueCodes { nationalBibliography otherCatalogues }
        titles { main }
        materialSelection {
            selectionGroup { type display }
        }
        subjects {
            dbcVerified { type display local }
        }
        series { title numberInSeries }
    }
}
