INSERT INTO subject(id, name, path, parentid) VALUES(57, 'Voksen', 'Voksen', NULL) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(58, 'Børn/skole', 'Børn/skole', NULL) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(121, 'Multimedier', 'Multimedier', NULL) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1341, 'Film', 'Film', NULL) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(61, 'Digte', 'Voksen/Digte', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(62, 'Drama', 'Voksen/Drama', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(63, 'Læsehandicap', 'Voksen/Læsehandicap', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(64, 'Noveller, antologier', 'Voksen/Noveller, antologier', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(65, 'Tegneserie', 'Voksen/Tegneserie', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(66, 'Roman', 'Voksen/Roman', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(67, 'Ledig gruppe', 'Voksen/Ledig gruppe', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(68, '00-07', 'Voksen/00-07', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(69, '10-19', 'Voksen/10-19', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(70, '20-29', 'Voksen/20-29', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(71, '30-39', 'Voksen/30-39', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(72, '40-49', 'Voksen/40-49', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(73, '50-59', 'Voksen/50-59', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(74, '60-69', 'Voksen/60-69', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(75, '70-79', 'Voksen/70-79', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(76, '80-89', 'Voksen/80-89', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(77, '90-99', 'Voksen/90-99', 57) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(101, '3. og 4. verden', 'Voksen/Roman/3. og 4. verden', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(102, 'Arbejde, hverdag, samfund', 'Voksen/Roman/Arbejde, hverdag, samfund', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(104, 'Biografisk', 'Voksen/Roman/Biografisk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(106, 'Dyr', 'Voksen/Roman/Dyr', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(108, 'Fantasy', 'Voksen/Roman/Fantasy', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(109, 'Historisk', 'Voksen/Roman/Historisk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(111, 'Homoseksualitet', 'Voksen/Roman/Homoseksualitet', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(112, 'Humor, satire', 'Voksen/Roman/Humor, satire', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(123, 'Klassiker', 'Voksen/Roman/Klassiker', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(141, 'Horror, gys', 'Voksen/Roman/Horror, gys', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(143, 'Krimi, spænding', 'Voksen/Roman/Krimi, spænding', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(144, 'Kvinder', 'Voksen/Roman/Kvinder', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(146, 'Kærlighed', 'Voksen/Roman/Kærlighed', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(147, 'Livet på landet', 'Voksen/Roman/Livet på landet', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(149, 'Mænd', 'Voksen/Roman/Mænd', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(150, 'Natur', 'Voksen/Roman/Natur', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(152, 'Erotik', 'Voksen/Roman/Erotik', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(153, 'Psykologisk', 'Voksen/Roman/Psykologisk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(154, 'Religiøs', 'Voksen/Roman/Religiøs', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(156, 'Science fiction', 'Voksen/Roman/Science fiction', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(157, 'Slægtsroman', 'Voksen/Roman/Slægtsroman', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(159, 'Sygdom', 'Voksen/Roman/Sygdom', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(162, 'Trivi', 'Voksen/Roman/Trivi', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(163, 'Overs: Afrikansk', 'Voksen/Roman/Overs: Afrikansk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(165, 'Overs: Amerikansk', 'Voksen/Roman/Overs: Amerikansk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(166, 'Overs: Engelsk', 'Voksen/Roman/Overs: Engelsk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(168, 'Overs: Tysk', 'Voksen/Roman/Overs: Tysk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(169, 'Overs: Fransk', 'Voksen/Roman/Overs: Fransk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(171, 'Overs: Grønlandsk, islandsk, færøsk', 'Voksen/Roman/Overs: Grønlandsk, islandsk, færøsk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(172, 'Overs: Hebraisk, jiddisch', 'Voksen/Roman/Overs: Hebraisk, jiddisch', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(174, 'Overs: Italiensk', 'Voksen/Roman/Overs: Italiensk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(175, 'Overs: Latinamerikansk', 'Voksen/Roman/Overs: Latinamerikansk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(177, 'Overs: Kinesisk, japansk', 'Voksen/Roman/Overs: Kinesisk, japansk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(178, 'Overs: Nordisk', 'Voksen/Roman/Overs: Nordisk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(180, 'Overs: Spansk', 'Voksen/Roman/Overs: Spansk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(181, '00', 'Voksen/00-07/00', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(183, '01 Bibliografi', 'Voksen/00-07/01 Bibliografi', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(184, '02 Biblioteks- og arkivvæsen', 'Voksen/00-07/02 Biblioteks- og arkivvæsen', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(186, '03 Leksika', 'Voksen/00-07/03 Leksika', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(187, '04 Essays', 'Voksen/00-07/04 Essays', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(189, '05 Aviser. Periodica', 'Voksen/00-07/05 Aviser. Periodica', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(190, '06 Museumsvæsen', 'Voksen/00-07/06 Museumsvæsen', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(192, '07 Pressevæsen', 'Voksen/00-07/07 Pressevæsen', 68) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(195, '10 Filosofi', 'Voksen/10-19/10 Filosofi', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(196, '11 Logik', 'Voksen/10-19/11 Logik', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(198, '12 Erkendelsesteori', 'Voksen/10-19/12 Erkendelsesteori', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(200, '13 Psykologi', 'Voksen/10-19/13 Psykologi', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(202, '14 Okkultisme', 'Voksen/10-19/14 Okkultisme', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(203, '15 Etik', 'Voksen/10-19/15 Etik', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(205, '16 Religionsfilosofi', 'Voksen/10-19/16 Religionsfilosofi', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(207, '17 Æstetik', 'Voksen/10-19/17 Æstetik', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(210, '19 Videnskab, edb', 'Voksen/10-19/19 Videnskab, edb', 69) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(211, '20 Kristendom', 'Voksen/20-29/20 Kristendom', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(212, '21 Naturlig teologi', 'Voksen/20-29/21 Naturlig teologi', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(213, '22 Bibelen', 'Voksen/20-29/22 Bibelen', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(214, '23 Dogmatik', 'Voksen/20-29/23 Dogmatik', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(216, '24 Trosliv', 'Voksen/20-29/24 Trosliv', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(218, '25 Mission', 'Voksen/20-29/25 Mission', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(219, '26 Kirkens institutioner', 'Voksen/20-29/26 Kirkens institutioner', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(221, '27 Kirkehistorie', 'Voksen/20-29/27 Kirkehistorie', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(222, '28 Kristne kirker og sekter', 'Voksen/20-29/28 Kristne kirker og sekter', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(224, '29 Religionsvidenskab. Andre religioner', 'Voksen/20-29/29 Religionsvidenskab. Andre religioner', 70) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(226, '30 Samfund. Sociologi', 'Voksen/30-39/30 Samfund. Sociologi', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(227, '31 Statistik. Demografi', 'Voksen/30-39/31 Statistik. Demografi', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(228, '32 Politik', 'Voksen/30-39/32 Politik', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(229, '33 Økonomi', 'Voksen/30-39/33 Økonomi', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(230, '34 Lov og ret', 'Voksen/30-39/34 Lov og ret', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(231, '35 Offentlig forvaltning', 'Voksen/30-39/35 Offentlig forvaltning', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(232, '36 Lokalforvaltning', 'Voksen/30-39/36 Lokalforvaltning', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(233, '37 Uddannelse', 'Voksen/30-39/37 Uddannelse', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(234, '38 Forsikring. Omsorg', 'Voksen/30-39/38 Forsikring. Omsorg', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(235, '39 Folkekultur', 'Voksen/30-39/39 Folkekultur', 71) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(236, '40 Kort og atlas', 'Voksen/40-49/40 Kort og atlas', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(237, '41 Europa', 'Voksen/40-49/41 Europa', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(238, '42 Frankrig', 'Voksen/40-49/42 Frankrig', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(239, '43 England', 'Voksen/40-49/43 England', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(240, '44 Mellemeuropa', 'Voksen/40-49/44 Mellemeuropa', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(241, '45 Norden', 'Voksen/40-49/45 Norden', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(242, '46 Danmark', 'Voksen/40-49/46 Danmark', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(243, '47 Andre euopæiske lande', 'Voksen/40-49/47 Andre euopæiske lande', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(244, '48 Andre verdensdele', 'Voksen/40-49/48 Andre verdensdele', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(245, '49 Polarlandene', 'Voksen/40-49/49 Polarlandene', 72) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(246, '50 Naturvidenskab', 'Voksen/50-59/50 Naturvidenskab', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(247, '51 Matematik', 'Voksen/50-59/51 Matematik', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(248, '52 Astronomi', 'Voksen/50-59/52 Astronomi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(249, '53 Fysik og kemi', 'Voksen/50-59/53 Fysik og kemi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(250, '54 Kemi', 'Voksen/50-59/54 Kemi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(251, '55 Geologi. Geofysik', 'Voksen/50-59/55 Geologi. Geofysik', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(252, '56 Biologi', 'Voksen/50-59/56 Biologi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(253, '57 Botanik', 'Voksen/50-59/57 Botanik', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(254, '58 Zoologi', 'Voksen/50-59/58 Zoologi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(255, '59 Antropologi', 'Voksen/50-59/59 Antropologi', 73) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(256, '60 Teknik. Ledelse', 'Voksen/60-69/60 Teknik. Ledelse', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(257, '61 Medicin', 'Voksen/60-69/61 Medicin', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(258, '62 Maskinlære. Elektroteknik', 'Voksen/60-69/62 Maskinlære. Elektroteknik', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(259, '63 Land-skov-havebrug. Fiskeri', 'Voksen/60-69/63 Land-skov-havebrug. Fiskeri', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(260, '64 Kogebøger', 'Voksen/60-69/64 Kogebøger', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(261, '65 Samfærdsel. Handel', 'Voksen/60-69/65 Samfærdsel. Handel', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(262, '66 Kemisk industri', 'Voksen/60-69/66 Kemisk industri', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(263, '67 Mekanisk industri', 'Voksen/60-69/67 Mekanisk industri', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(264, '68 Håndværk', 'Voksen/60-69/68 Håndværk', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(265, '69 Byggeteknik', 'Voksen/60-69/69 Byggeteknik', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(266, '70 Kunst i alm.', 'Voksen/70-79/70 Kunst i alm.', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(267, '71 Arkitektur', 'Voksen/70-79/71 Arkitektur', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(268, '72 Enkelte kunstneres værker', 'Voksen/70-79/72 Enkelte kunstneres værker', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(269, '73 Skulptur', 'Voksen/70-79/73 Skulptur', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(270, '74 Malerkunst. Tegnekunst', 'Voksen/70-79/74 Malerkunst. Tegnekunst', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(271, '75 Grafisk kunst. Fotografi', 'Voksen/70-79/75 Grafisk kunst. Fotografi', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(272, '76 Kunsthåndværk. Antikviteter', 'Voksen/70-79/76 Kunsthåndværk. Antikviteter', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(273, '77 Teater, film, tv', 'Voksen/70-79/77 Teater, film, tv', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(274, '78 Musik', 'Voksen/70-79/78 Musik', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(275, '79 Forlystelser. Spil. Idræt', 'Voksen/70-79/79 Forlystelser. Spil. Idræt', 75) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(276, '80 Litteraturteori', 'Voksen/80-89/80 Litteraturteori', 76) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(277, '81 Litteraturhistorie', 'Voksen/80-89/81 Litteraturhistorie', 76) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(285, '89 Sprog', 'Voksen/80-89/89 Sprog', 76) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(286, '90 Historie i alm. Kulturhistorie', 'Voksen/90-99/90 Historie i alm. Kulturhistorie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(287, '91 Historiske perioder', 'Voksen/90-99/91 Historiske perioder', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(288, '92 Frankrigs historie', 'Voksen/90-99/92 Frankrigs historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(289, '93 Englands historie', 'Voksen/90-99/93 Englands historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(290, '94 Mellemeuropas historie', 'Voksen/90-99/94 Mellemeuropas historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(291, '95 Nordens historie', 'Voksen/90-99/95 Nordens historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(292, '96 Danmarkshistorie', 'Voksen/90-99/96 Danmarkshistorie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(293, '97 Andre europæiske landes historie', 'Voksen/90-99/97 Andre europæiske landes historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(294, '98 Andre verdensdeles historie', 'Voksen/90-99/98 Andre verdensdeles historie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(295, '99 Personalhistorie', 'Voksen/90-99/99 Personalhistorie', 77) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(296, 'Billedbog', 'Børn/skole/Billedbog', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(297, 'Digte', 'Børn/skole/Digte', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(298, 'Drama', 'Børn/skole/Drama', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(299, 'Fagbilledbog - børn', 'Børn/skole/Fagbilledbog - børn', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(300, 'Fagbilledbog - skole', 'Børn/skole/Fagbilledbog - skole', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(301, 'Letlæsning, pæd. tilr.', 'Børn/skole/Letlæsning, pæd. tilr.', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(302, 'Noveller/antologier', 'Børn/skole/Noveller/antologier', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(303, 'Letlæsning, engelsk', 'Børn/skole/Letlæsning, engelsk', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(304, 'Tegneserie', 'Børn/skole/Tegneserie', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(305, 'Ungdomsbog, young adult', 'Børn/skole/Ungdomsbog, young adult', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(306, 'Roman', 'Børn/skole/Roman', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(307, 'Andre lande', 'Børn/skole/Roman/Andre lande', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(308, 'Du er hovedperson', 'Børn/skole/Roman/Du er hovedperson', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(309, 'Dyr', 'Børn/skole/Roman/Dyr', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(310, 'Eksperimenterende', 'Børn/skole/Roman/Eksperimenterende', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(311, 'Fantasy', 'Børn/skole/Roman/Fantasy', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(312, 'Eventyr', 'Børn/skole/Roman/Eventyr', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(313, 'Historiske', 'Børn/skole/Roman/Historiske', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(314, 'Humor', 'Børn/skole/Roman/Humor', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(315, 'Hverdag, familie, søskende', 'Børn/skole/Roman/Hverdag, familie, søskende', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(316, 'Drenge, venner', 'Børn/skole/Roman/Drenge, venner', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(317, 'Indvandrere', 'Børn/skole/Roman/Indvandrere', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(318, 'Klassikere', 'Børn/skole/Roman/Klassikere', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(319, 'Horror, gys', 'Børn/skole/Roman/Horror, gys', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(320, 'Krimi, spænding', 'Børn/skole/Roman/Krimi, spænding', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(321, 'Natur', 'Børn/skole/Roman/Natur', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(322, 'Religiøse', 'Børn/skole/Roman/Religiøse', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(323, 'Sagn, saga', 'Børn/skole/Roman/Sagn, saga', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(324, 'Science fiction', 'Børn/skole/Roman/Science fiction', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(325, 'Sport, idræt', 'Børn/skole/Roman/Sport, idræt', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(326, 'Trivi', 'Børn/skole/Roman/Trivi', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(327, '00-07', 'Børn/skole/00-07', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(328, '10-19', 'Børn/skole/10-19', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(329, '20-29', 'Børn/skole/20-29', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(330, '30-39', 'Børn/skole/30-39', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(331, '40-49', 'Børn/skole/40-49', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(332, '50-59', 'Børn/skole/50-59', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(333, '60-69', 'Børn/skole/60-69', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(334, '70-79', 'Børn/skole/70-79', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(335, '80-89', 'Børn/skole/80-89', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(336, '90-99', 'Børn/skole/90-99', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(337, '01 Bibliografi', 'Børn/skole/00-07/01 Bibliografi', 327) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(338, '02 Biblioteks- og arkivvæsen', 'Børn/skole/00-07/02 Biblioteks- og arkivvæsen', 327) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(339, '03 Leksika', 'Børn/skole/00-07/03 Leksika', 327) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(340, '07 Pressevæsen', 'Børn/skole/00-07/07 Pressevæsen', 327) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(341, '10 Filosofi', 'Børn/skole/10-19/10 Filosofi', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(342, '11 Logik', 'Børn/skole/10-19/11 Logik', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(343, '12 Erkendelsesteori', 'Børn/skole/10-19/12 Erkendelsesteori', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(344, '13 Psykologi', 'Børn/skole/10-19/13 Psykologi', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(345, '14 Okkultisme', 'Børn/skole/10-19/14 Okkultisme', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(346, '15 Etik', 'Børn/skole/10-19/15 Etik', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(347, '16 Religionsfilosofi', 'Børn/skole/10-19/16 Religionsfilosofi', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(348, '17 Æstetik', 'Børn/skole/10-19/17 Æstetik', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(350, '19 Videnskab. Edb', 'Børn/skole/10-19/19 Videnskab. Edb', 328) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(351, '20 Kristendom', 'Børn/skole/20-29/20 Kristendom', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(352, '21 Naturlig teologi', 'Børn/skole/20-29/21 Naturlig teologi', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(353, '22 Bibelen', 'Børn/skole/20-29/22 Bibelen', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(354, '23 Dogmatik', 'Børn/skole/20-29/23 Dogmatik', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(355, '24 Trosliv. Opbyggelse', 'Børn/skole/20-29/24 Trosliv. Opbyggelse', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(356, '25 Mission', 'Børn/skole/20-29/25 Mission', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(357, '26 Kirkens institutioner', 'Børn/skole/20-29/26 Kirkens institutioner', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(358, '27 Kirkehistorie', 'Børn/skole/20-29/27 Kirkehistorie', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(359, '28 Kristne kirker og sekter', 'Børn/skole/20-29/28 Kristne kirker og sekter', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(360, '29 Religionsvidenskab. Andre religioner', 'Børn/skole/20-29/29 Religionsvidenskab. Andre religioner', 329) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(361, '30 Samfundvidenskab. Sociologi', 'Børn/skole/30-39/30 Samfundvidenskab. Sociologi', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(362, '31 Statistik. Demografi', 'Børn/skole/30-39/31 Statistik. Demografi', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(363, '32 Politik', 'Børn/skole/30-39/32 Politik', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(364, '33 Økonomi', 'Børn/skole/30-39/33 Økonomi', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(365, '34 Lov og ret', 'Børn/skole/30-39/34 Lov og ret', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(366, '35 Statsforvaltning', 'Børn/skole/30-39/35 Statsforvaltning', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(367, '36 Lokalforvaltning', 'Børn/skole/30-39/36 Lokalforvaltning', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(368, '37 Uddannelse', 'Børn/skole/30-39/37 Uddannelse', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(369, '38 Forsikring. Omsorg', 'Børn/skole/30-39/38 Forsikring. Omsorg', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(370, '39 Folkekultur', 'Børn/skole/30-39/39 Folkekultur', 330) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(371, '40 Geografi og rejser i alm.', 'Børn/skole/40-49/40 Geografi og rejser i alm.', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(372, '41 Europa', 'Børn/skole/40-49/41 Europa', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(373, '42 Frankrig', 'Børn/skole/40-49/42 Frankrig', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(374, '43 England', 'Børn/skole/40-49/43 England', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(375, '44 Mellemeuropa', 'Børn/skole/40-49/44 Mellemeuropa', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(376, '45 Norden', 'Børn/skole/40-49/45 Norden', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(377, '46 Danmark', 'Børn/skole/40-49/46 Danmark', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(378, '47 Andre europæiske lande', 'Børn/skole/40-49/47 Andre europæiske lande', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(379, '48 Andre verdensdele', 'Børn/skole/40-49/48 Andre verdensdele', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(380, '49 Polarlandene', 'Børn/skole/40-49/49 Polarlandene', 331) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(381, '50 Naturvidenskab', 'Børn/skole/50-59/50 Naturvidenskab', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(382, '51 Matematik', 'Børn/skole/50-59/51 Matematik', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(383, '52 Astronomi', 'Børn/skole/50-59/52 Astronomi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(384, '53 Fysik og kemi', 'Børn/skole/50-59/53 Fysik og kemi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(385, '54 Kemi', 'Børn/skole/50-59/54 Kemi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(386, '55 Geologi og geofysik', 'Børn/skole/50-59/55 Geologi og geofysik', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(387, '56 Biologi', 'Børn/skole/50-59/56 Biologi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(388, '57 Botanik', 'Børn/skole/50-59/57 Botanik', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(389, '58 Zoologi', 'Børn/skole/50-59/58 Zoologi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(390, '59 Antropologi', 'Børn/skole/50-59/59 Antropologi', 332) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(391, '60 Teknik i alm.', 'Børn/skole/60-69/60 Teknik i alm.', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(392, '61 Medicin', 'Børn/skole/60-69/61 Medicin', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(393, '62 Maskinlære. Varmeteknik. Elektroteknik', 'Børn/skole/60-69/62 Maskinlære. Varmeteknik. Elektroteknik', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(394, '63 Land-, have- og skovbrug. Fiskeri', 'Børn/skole/60-69/63 Land-, have- og skovbrug. Fiskeri', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(395, '64 Hjem og husholdning', 'Børn/skole/60-69/64 Hjem og husholdning', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(396, '65 Handel. Søfart', 'Børn/skole/60-69/65 Handel. Søfart', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(397, '66 Kemisk industri', 'Børn/skole/60-69/66 Kemisk industri', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(398, '67 Mekanisk industri', 'Børn/skole/60-69/67 Mekanisk industri', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(399, '68 Håndværk', 'Børn/skole/60-69/68 Håndværk', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(400, '69 Byggeteknik', 'Børn/skole/60-69/69 Byggeteknik', 333) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(401, '70 Kunst. Kunstteori', 'Børn/skole/70-79/70 Kunst. Kunstteori', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(402, '71 Arkitektur', 'Børn/skole/70-79/71 Arkitektur', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(403, '72 Enkelte kunstneres værker', 'Børn/skole/70-79/72 Enkelte kunstneres værker', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(404, '73 Skulptur', 'Børn/skole/70-79/73 Skulptur', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(405, '74 Malerkunst. Tegnekunst', 'Børn/skole/70-79/74 Malerkunst. Tegnekunst', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(406, '75 Grafisk kunst. Fotografi', 'Børn/skole/70-79/75 Grafisk kunst. Fotografi', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(407, '76 Kunsthåndværk. Antikviteter', 'Børn/skole/70-79/76 Kunsthåndværk. Antikviteter', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(408, '77 Teater. Film. Radio. Tv', 'Børn/skole/70-79/77 Teater. Film. Radio. Tv', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(409, '78 Musik', 'Børn/skole/70-79/78 Musik', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(410, '79 Forlystelser. Spil. Idræt', 'Børn/skole/70-79/79 Forlystelser. Spil. Idræt', 334) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(411, '80 Litteraturteori', 'Børn/skole/80-89/80 Litteraturteori', 335) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(412, '81 Litteraturhistorie', 'Børn/skole/80-89/81 Litteraturhistorie', 335) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(420, '89 Sprog', 'Børn/skole/80-89/89 Sprog', 335) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(421, '90 Historie i alm.', 'Børn/skole/90-99/90 Historie i alm.', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(422, '91 Enkelte historiske perioder', 'Børn/skole/90-99/91 Enkelte historiske perioder', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(423, '92 Frankrigs historie', 'Børn/skole/90-99/92 Frankrigs historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(424, '93 Englands historie', 'Børn/skole/90-99/93 Englands historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(425, '94 Mellemeuropas historie', 'Børn/skole/90-99/94 Mellemeuropas historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(426, '95 Nordens historie', 'Børn/skole/90-99/95 Nordens historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(427, '96 Danmarkshistorie', 'Børn/skole/90-99/96 Danmarkshistorie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(428, '97 Andre europæiske landes historie', 'Børn/skole/90-99/97 Andre europæiske landes historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(429, '98 Andre verdensdeles historie', 'Børn/skole/90-99/98 Andre verdensdeles historie', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(430, '99 Personalhistorie. Genealogi', 'Børn/skole/90-99/99 Personalhistorie. Genealogi', 336) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(461, 'Børn', 'Multimedier/Børn', 121) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(462, 'Voksen', 'Multimedier/Voksen', 121) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(711, 'Danske', 'Voksen/Roman/Danske', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(712, 'Overs: Østeuropæisk', 'Voksen/Roman/Overs: Østeuropæisk', 66) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1351, 'Spillefilm/voksne', 'Film/Spillefilm/voksne', 1341) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1353, 'Actionfilm', 'Film/Spillefilm/voksne/Actionfilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1354, 'Adventurefilm', 'Film/Spillefilm/voksne/Adventurefilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1355, 'Biografiske film', 'Film/Spillefilm/voksne/Biografiske film', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1356, 'Drama', 'Film/Spillefilm/voksne/Drama', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1357, 'Erotiske film', 'Film/Spillefilm/voksne/Erotiske film', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1358, 'Eventyr', 'Film/Spillefilm/voksne/Eventyr', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1359, 'Farcer', 'Film/Spillefilm/voksne/Farcer', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1360, 'Folkekomedier', 'Film/Spillefilm/voksne/Folkekomedier', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1361, 'Gyserfilm', 'Film/Spillefilm/voksne/Gyserfilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1362, 'Katastrofefilm', 'Film/Spillefilm/voksne/Katastrofefilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1363, 'Komedier', 'Film/Spillefilm/voksne/Komedier', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1364, 'Krigsfilm', 'Film/Spillefilm/voksne/Krigsfilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1365, 'Krimi', 'Film/Spillefilm/voksne/Krimi', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1366, 'Kærlighedsfilm', 'Film/Spillefilm/voksne/Kærlighedsfilm', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1367, 'Musicals', 'Film/Spillefilm/voksne/Musicals', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1368, 'Road movies', 'Film/Spillefilm/voksne/Road movies', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1369, 'Science fiction', 'Film/Spillefilm/voksne/Science fiction', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1370, 'Socialrealisme', 'Film/Spillefilm/voksne/Socialrealisme', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1371, 'Tragedier', 'Film/Spillefilm/voksne/Tragedier', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1372, 'Westerns', 'Film/Spillefilm/voksne/Westerns', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1373, 'Fagfilm/voksne', 'Film/Fagfilm/voksne', 1341) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1374, '00-07', 'Film/Fagfilm/voksne/00-07', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1375, '10-19', 'Film/Fagfilm/voksne/10-19', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1376, '20-29', 'Film/Fagfilm/voksne/20-29', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1377, '30-39', 'Film/Fagfilm/voksne/30-39', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1378, '40-49', 'Film/Fagfilm/voksne/40-49', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1379, '50-59', 'Film/Fagfilm/voksne/50-59', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1380, '60-69', 'Film/Fagfilm/voksne/60-69', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1381, '70-79', 'Film/Fagfilm/voksne/70-79', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1382, '80-89', 'Film/Fagfilm/voksne/80-89', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1383, '90-99', 'Film/Fagfilm/voksne/90-99', 1373) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1384, '00 Bogvæsen og boghåndværk', 'Film/Fagfilm/voksne/00-07/00 Bogvæsen og boghåndværk', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1385, '01 Bibliografi', 'Film/Fagfilm/voksne/00-07/01 Bibliografi', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1386, '02 Biblioteks- og arkivvæsen', 'Film/Fagfilm/voksne/00-07/02 Biblioteks- og arkivvæsen', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1387, '03 Encyklopædier', 'Film/Fagfilm/voksne/00-07/03 Encyklopædier', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1388, '04 Samlinger. Værker af blandte indhold', 'Film/Fagfilm/voksne/00-07/04 Samlinger. Værker af blandte indhold', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1389, '05 Aviser', 'Film/Fagfilm/voksne/00-07/05 Aviser', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1390, '06 Museumsværker i alm.', 'Film/Fagfilm/voksne/00-07/06 Museumsværker i alm.', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1391, '07 Pressevæsen', 'Film/Fagfilm/voksne/00-07/07 Pressevæsen', 1374) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1392, '10 Filosofi', 'Film/Fagfilm/voksne/10-19/10 Filosofi', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1393, '11 Logik', 'Film/Fagfilm/voksne/10-19/11 Logik', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1394, '12 Erkendelsesteori', 'Film/Fagfilm/voksne/10-19/12 Erkendelsesteori', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1395, '13 Psykologi', 'Film/Fagfilm/voksne/10-19/13 Psykologi', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1396, '14 Okkultisme', 'Film/Fagfilm/voksne/10-19/14 Okkultisme', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1397, '15 Etik', 'Film/Fagfilm/voksne/10-19/15 Etik', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1398, '16 Religionsfilosofi', 'Film/Fagfilm/voksne/10-19/16 Religionsfilosofi', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1399, '17 Æstetik', 'Film/Fagfilm/voksne/10-19/17 Æstetik', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1400, '19 Videnskab og forskning', 'Film/Fagfilm/voksne/10-19/19 Videnskab og forskning', 1375) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1401, '20 Kristen religion', 'Film/Fagfilm/voksne/20-29/20 Kristen religion', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1402, '21 Naturlig teologi', 'Film/Fagfilm/voksne/20-29/21 Naturlig teologi', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1403, '22 Bibelen', 'Film/Fagfilm/voksne/20-29/22 Bibelen', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1405, '23 Dogmatik', 'Film/Fagfilm/voksne/20-29/23 Dogmatik', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1406, '24 Trosliv', 'Film/Fagfilm/voksne/20-29/24 Trosliv', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1407, '25 Mission', 'Film/Fagfilm/voksne/20-29/25 Mission', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1408, '26 Kirkens institutioner', 'Film/Fagfilm/voksne/20-29/26 Kirkens institutioner', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1409, '27 Kirkehistorie', 'Film/Fagfilm/voksne/20-29/27 Kirkehistorie', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1410, '28 Kristne kirker', 'Film/Fagfilm/voksne/20-29/28 Kristne kirker', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1411, '29 Religionsvidenskab', 'Film/Fagfilm/voksne/20-29/29 Religionsvidenskab', 1376) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1412, '30 Samfundsvidenskab', 'Film/Fagfilm/voksne/30-39/30 Samfundsvidenskab', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1413, '31 Statistik. Demografi', 'Film/Fagfilm/voksne/30-39/31 Statistik. Demografi', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1414, '32 Politik', 'Film/Fagfilm/voksne/30-39/32 Politik', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1415, '33 Økonomi', 'Film/Fagfilm/voksne/30-39/33 Økonomi', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1416, '34 Lov og ret', 'Film/Fagfilm/voksne/30-39/34 Lov og ret', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1417, '35 Statsforvaltning', 'Film/Fagfilm/voksne/30-39/35 Statsforvaltning', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1418, '36 Lokalforvaltning', 'Film/Fagfilm/voksne/30-39/36 Lokalforvaltning', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1419, '37 Uddannelse', 'Film/Fagfilm/voksne/30-39/37 Uddannelse', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1420, '38 Forsikring. Forsorg', 'Film/Fagfilm/voksne/30-39/38 Forsikring. Forsorg', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1421, '39 Folkekultur', 'Film/Fagfilm/voksne/30-39/39 Folkekultur', 1377) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1422, '40 Geografi og rejser', 'Film/Fagfilm/voksne/40-49/40 Geografi og rejser', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1423, '41 Europa', 'Film/Fagfilm/voksne/40-49/41 Europa', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1424, '42 Frankrig', 'Film/Fagfilm/voksne/40-49/42 Frankrig', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1425, '43 England', 'Film/Fagfilm/voksne/40-49/43 England', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1426, '44 Mellemeuropa', 'Film/Fagfilm/voksne/40-49/44 Mellemeuropa', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1427, '45 Norden', 'Film/Fagfilm/voksne/40-49/45 Norden', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1428, '46 Danmark', 'Film/Fagfilm/voksne/40-49/46 Danmark', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1429, '47 Andre europæiske lande', 'Film/Fagfilm/voksne/40-49/47 Andre europæiske lande', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1430, '48 Andre verdensdele', 'Film/Fagfilm/voksne/40-49/48 Andre verdensdele', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1431, '49 Polarlandene', 'Film/Fagfilm/voksne/40-49/49 Polarlandene', 1378) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1432, '50 Naturvidenskab', 'Film/Fagfilm/voksne/50-59/50 Naturvidenskab', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1433, '51 Matematik', 'Film/Fagfilm/voksne/50-59/51 Matematik', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1434, '52 Astronomi', 'Film/Fagfilm/voksne/50-59/52 Astronomi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1435, '53 Fysik og kemi', 'Film/Fagfilm/voksne/50-59/53 Fysik og kemi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1436, '54 Kemi', 'Film/Fagfilm/voksne/50-59/54 Kemi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1437, '55 Geologi', 'Film/Fagfilm/voksne/50-59/55 Geologi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1438, '56 Biologi', 'Film/Fagfilm/voksne/50-59/56 Biologi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1439, '57 Botanik', 'Film/Fagfilm/voksne/50-59/57 Botanik', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1440, '58 Zoologi', 'Film/Fagfilm/voksne/50-59/58 Zoologi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1441, '59 Antropologi', 'Film/Fagfilm/voksne/50-59/59 Antropologi', 1379) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1442, '60 Teknik. Ledelse', 'Film/Fagfilm/voksne/60-69/60 Teknik. Ledelse', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1443, '61 Medicin', 'Film/Fagfilm/voksne/60-69/61 Medicin', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1444, '62 Maskinlære', 'Film/Fagfilm/voksne/60-69/62 Maskinlære', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1445, '63 Havebrug. Landbrug', 'Film/Fagfilm/voksne/60-69/63 Havebrug. Landbrug', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1446, '64 Hjem og husholdning', 'Film/Fagfilm/voksne/60-69/64 Hjem og husholdning', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1447, '65 Handel. Færdsel. Søfart', 'Film/Fagfilm/voksne/60-69/65 Handel. Færdsel. Søfart', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1448, '66 Kemisk industri', 'Film/Fagfilm/voksne/60-69/66 Kemisk industri', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1449, '67 Mekaniske industrier', 'Film/Fagfilm/voksne/60-69/67 Mekaniske industrier', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1450, '68 Håndværk', 'Film/Fagfilm/voksne/60-69/68 Håndværk', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1451, '69 Byggeteknik', 'Film/Fagfilm/voksne/60-69/69 Byggeteknik', 1380) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1452, '70 Kunst', 'Film/Fagfilm/voksne/70-79/70 Kunst', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1453, '71 Arkitektur', 'Film/Fagfilm/voksne/70-79/71 Arkitektur', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1454, '72 Enkelte kunstneres værker', 'Film/Fagfilm/voksne/70-79/72 Enkelte kunstneres værker', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1455, '73 Skulptur', 'Film/Fagfilm/voksne/70-79/73 Skulptur', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1456, '74 Malerkunst. Tegnekunst', 'Film/Fagfilm/voksne/70-79/74 Malerkunst. Tegnekunst', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1457, '75 Grafisk kunst', 'Film/Fagfilm/voksne/70-79/75 Grafisk kunst', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1458, '76 Kunsthåndværk', 'Film/Fagfilm/voksne/70-79/76 Kunsthåndværk', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1459, '77 Teater. Film. Radio. Tv', 'Film/Fagfilm/voksne/70-79/77 Teater. Film. Radio. Tv', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1460, '78 Musik', 'Film/Fagfilm/voksne/70-79/78 Musik', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1461, '79 Forlystelser. Spil', 'Film/Fagfilm/voksne/70-79/79 Forlystelser. Spil', 1381) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1462, '80 Litteraturteori', 'Film/Fagfilm/voksne/80-89/80 Litteraturteori', 1382) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1463, '81 Litteraturhistorie', 'Film/Fagfilm/voksne/80-89/81 Litteraturhistorie', 1382) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1464, '89 Sprog', 'Film/Fagfilm/voksne/80-89/89 Sprog', 1382) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1465, '90 Historie', 'Film/Fagfilm/voksne/90-99/90 Historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1466, '91 Enkelte historiske perioder', 'Film/Fagfilm/voksne/90-99/91 Enkelte historiske perioder', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1467, '92 Frankrigs historie', 'Film/Fagfilm/voksne/90-99/92 Frankrigs historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1468, '93 Englands historie', 'Film/Fagfilm/voksne/90-99/93 Englands historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1469, '94 Mellemeuropas historie', 'Film/Fagfilm/voksne/90-99/94 Mellemeuropas historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1470, '95 Nordens historie', 'Film/Fagfilm/voksne/90-99/95 Nordens historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1471, '96 Danmarks historie', 'Film/Fagfilm/voksne/90-99/96 Danmarks historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1472, '97 Andre europæiske landes historie', 'Film/Fagfilm/voksne/90-99/97 Andre europæiske landes historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1473, '98 Andre verdensdeles historie', 'Film/Fagfilm/voksne/90-99/98 Andre verdensdeles historie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1474, '99 Personalhistorie', 'Film/Fagfilm/voksne/90-99/99 Personalhistorie', 1383) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1491, 'Actionspil', 'Multimedier/Børn/Actionspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1492, 'Adventurespil', 'Multimedier/Børn/Adventurespil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1493, 'Arkadespil', 'Multimedier/Børn/Arkadespil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1494, 'Hovedbrudsspil', 'Multimedier/Børn/Hovedbrudsspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1495, 'Karaokespil', 'Multimedier/Børn/Karaokespil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1496, 'Leg', 'Multimedier/Børn/Leg', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1497, 'Leg og lær', 'Multimedier/Børn/Leg og lær', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1499, 'Managerspil', 'Multimedier/Børn/Managerspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1500, 'Minispil', 'Multimedier/Børn/Minispil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1501, 'MMORGP', 'Multimedier/Børn/MMORGP', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1502, 'MMTRPS', 'Multimedier/Børn/MMTRPS', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1503, 'Platformsspil', 'Multimedier/Børn/Platformsspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1504, 'Racerspil', 'Multimedier/Børn/Racerspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1505, 'Rollespil', 'Multimedier/Børn/Rollespil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1506, 'Shoot-em-up', 'Multimedier/Børn/Shoot-em-up', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1507, 'Simulationsspil', 'Multimedier/Børn/Simulationsspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1508, 'Sportsspil', 'Multimedier/Børn/Sportsspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1509, 'Sprogkursus', 'Multimedier/Børn/Sprogkursus', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1510, 'Strategispil', 'Multimedier/Børn/Strategispil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1511, 'Undervisning', 'Multimedier/Børn/Undervisning', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1512, 'Værktøjsprogram', 'Multimedier/Børn/Værktøjsprogram', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1513, 'Actionspil', 'Multimedier/Voksen/Actionspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1514, 'Adventurespil', 'Multimedier/Voksen/Adventurespil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1515, 'Arkadespil', 'Multimedier/Voksen/Arkadespil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1516, 'Hovedbrudsspil', 'Multimedier/Voksen/Hovedbrudsspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1517, 'Karaokespil', 'Multimedier/Voksen/Karaokespil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1518, 'Leg', 'Multimedier/Voksen/Leg', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1519, 'Leg og lær', 'Multimedier/Voksen/Leg og lær', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1520, 'Lær selv', 'Multimedier/Voksen/Lær selv', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1521, 'Managerspil', 'Multimedier/Voksen/Managerspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1522, 'Minispil', 'Multimedier/Voksen/Minispil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1523, 'MMORGP', 'Multimedier/Voksen/MMORGP', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1524, 'MMTRPS', 'Multimedier/Voksen/MMTRPS', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1525, 'Platformsspil', 'Multimedier/Voksen/Platformsspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1526, 'Racerspil', 'Multimedier/Voksen/Racerspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1527, 'Rollespil', 'Multimedier/Voksen/Rollespil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1528, 'Shoot-em-up', 'Multimedier/Voksen/Shoot-em-up', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1529, 'Simulationsspil', 'Multimedier/Voksen/Simulationsspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1530, 'Sportsspil', 'Multimedier/Voksen/Sportsspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1531, 'Sprogkursus', 'Multimedier/Voksen/Sprogkursus', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1532, 'Strategispil', 'Multimedier/Voksen/Strategispil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1533, 'Undervisning', 'Multimedier/Voksen/Undervisning', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1534, 'Værktøjsprogram', 'Multimedier/Voksen/Værktøjsprogram', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1571, 'Fantasy', 'Multimedier/Børn/Fantasy', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1572, 'Kort- og brædtspil', 'Multimedier/Børn/Kort- og brædtspil', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1573, 'Lær selv', 'Multimedier/Børn/Lær selv', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1574, 'Shooter', 'Multimedier/Børn/Shooter', 461) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1576, 'Fantasy', 'Multimedier/Voksen/Fantasy', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1577, 'Kort- og brætspil', 'Multimedier/Voksen/Kort- og brætspil', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1578, 'Shooter', 'Multimedier/Voksen/Shooter', 462) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1591, 'tv-serier', 'Film/Spillefilm/voksne/tv-serier', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1611, 'Spillefilm/børn', 'Film/Spillefilm/børn', 1341) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1631, 'thriller', 'Film/Spillefilm/voksne/thriller', 1351) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1632, 'Actionfilm', 'Film/Spillefilm/børn/Actionfilm', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1633, 'Adventurefilm', 'Film/Spillefilm/børn/Adventurefilm', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1634, 'Biografiske film', 'Film/Spillefilm/børn/Biografiske film', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1635, 'Drama', 'Film/Spillefilm/børn/Drama', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1636, 'Eventyr', 'Film/Spillefilm/børn/Eventyr', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1637, 'Farcer', 'Film/Spillefilm/børn/Farcer', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1638, 'Folkekomedier', 'Film/Spillefilm/børn/Folkekomedier', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1639, 'Gyserfilm', 'Film/Spillefilm/børn/Gyserfilm', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1640, 'Katastrofefilm', 'Film/Spillefilm/børn/Katastrofefilm', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1641, 'Komedier', 'Film/Spillefilm/børn/Komedier', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1642, 'Krimi', 'Film/Spillefilm/børn/Krimi', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1643, 'Kærlighedsfilm', 'Film/Spillefilm/børn/Kærlighedsfilm', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1644, 'Musicals', 'Film/Spillefilm/børn/Musicals', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1645, 'Science fiction', 'Film/Spillefilm/børn/Science fiction', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1646, 'Socialrealisme', 'Film/Spillefilm/børn/Socialrealisme', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1647, 'Thriller', 'Film/Spillefilm/børn/Thriller', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1648, 'Tragedier', 'Film/Spillefilm/børn/Tragedier', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1649, 'Tv-serier', 'Film/Spillefilm/børn/Tv-serier', 1611) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1651, 'Piger, veninder', 'Børn/skole/Roman/Piger, veninder', 306) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1671, '64 Håndarbejde', 'Voksen/60-69/64 Håndarbejde', 74) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1672, 'Højtlæsning', 'Børn/skole/Højtlæsning', 58) ON CONFLICT DO NOTHING;
INSERT INTO subject(id, name, path, parentid) VALUES(1691, 'Fagfilm/børn', 'Film/Fagfilm/børn', 1341) ON CONFLICT DO NOTHING;
