#!/usr/bin/env bash

source "$(realpath $(dirname "${0}")/..)/scripts/common"

echo "### Stopping Promat local docker containers ###"

docker stop "${DOCKER_NAME}-${PORT}" 2>/dev/null || true
docker stop "${DOCKER_NAME}-database" 2>/dev/null || true
