openapi: 3.0.1
info:
  title: Promat service
  description: >-
    Provides backend services for the Promat system.
  license:
    name: GPL-3.0
    url: 'https://github.com/DBCDK/promat-service/blob/master/LICENCE.txt'
  version: 1.0-SNAPSHOT

tags:
  - name: reviewers
    description: Users writing professional reviews
  - name: subjects
    description: Fields of interests
  - name: records
    description: List of faustnumbers matching a given id
  - name: cases
    description: Cases
  - name: tasks
    description: Case tasks

paths:
  /reviewers:
    get:
      tags:
        - reviewers
      summary: Returns list of reviewers
      operationId: getReviewers
      parameters:
        - name: deadline
          in: query
          required: false
          description: Optional filter on deadline date as defined by RFC3339,
                       meaning only reviewers available for the deadline will be returned.
          schema:
            type: string
            format: date
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewerList'
        '400':
          description: bad request, invalid deadline date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

  /subjects:
    get:
      tags:
        - subjects
      summary: Returns list of all known subjects
      operationId: getSubjects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubjectList'

  /records/{id}:
    get:
      tags:
        - records
      summary: Return zero or more faust numbers that match the given id.
               The id can be a faust number or an isbn-10 or isbn-13 number.
      operationId: getRecords
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minimum: 1
            maximum: 1
            description: Identifier to lookup. Can be faust, isbn-10 or isbn-13
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordsList'
        '400':
          description: Error while resolving the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

  /cases:
    get:
      tags:
        - cases
      summary: Returns list of cases for the given faustnumber
      operationId: getCasesForFaust
      parameters:
        - in: query
          name: number
          required: true
          schema:
            type: string
            description: Faustnumber that most be covered by the cases returned
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaseSummaryList'
    post:
      tags:
        - cases
      summary: Create new case. (status field will be ignored if it exists.)
      operationId: createCase
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaseRequest'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '409':
          description: Conflict. A case with a status other than DONE or CLOSED already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

  /cases/{id}:
    get:
      tags:
        - cases
      summary: Returns a case with the given id
      operationId: getCase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: Case id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        '204':
          description: Case could not be found

    post:
      tags:
        - cases
      summary: Update an existing case
      operationId: updateCase
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: Case id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CaseRequest'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Case'
        '409':
          description: Case could not be updated, check ServiceError in body for specifics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

  /cases/{id}/tasks:
    post:
      tags:
        - tasks
      summary: Add task to case
      operationId: addTask
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            description: Case id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '409':
          description: Task could not be added, check ServiceError in body for specifics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'

components:
  schemas:
    Address:
      type: object
      properties:
        address1:
          type: string
        address2:
          type: string
        zip:
          type: string
        city:
          type: string
      required:
        - address1
        - zip
        - city

    ReviewerList:
      type: object
      properties:
        numFound:
          type: integer
        reviewers:
          type: array
          items:
            $ref: '#/components/schemas/Reviewer'
      required:
        - numFound
        - reviewers

    Reviewer:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        institution:
          type: string
        paycode:
          type: integer
        hiatus_begin:
          type: string
          format: date
        hiatus_end:
          type: string
          format: date
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'
      required:
        - id
        - firstName
        - lastName
        - email
        - address
        - institution
        - paycode
        - subjects

    ServiceError:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/ServiceErrorCode'
        cause:
          type: string
          description: Specific cause of the error,
                       for example the name of an invalid query parameter.
        details:
          type: string
      required:
        - code
        - cause

    ServiceErrorCode:
      type: string
      enum:
        - INVALID_QUERY_PARAM   # One of the query parameters is invalid
        - INVALID_REQUEST       # Request body contains invalid fields or id's
        - CASE_EXISTS           # Active case for this/these faust/fausts exists
        - INVALID_STATE         # Change to a new state was not possible or invalid
        - FAILED                # Some error occurred

    SubjectList:
      type: object
      properties:
        numFound:
          type: integer
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'
      required:
        - numFound
        - subjects

    Subject:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        parentId:
          type: integer
      required:
        - id
        - name

    RecordsList:
      type: object
      properties:
        numFound:
          type: integer
        records:
          type: array
          description: A list of faustnumbers matching the given id
          items:
            $ref: '#/components/schemas/Record'
      required:
        - numFound
        - records

    Record:
      type: object
      properties:
        faust:
          type: string
          description: Faustnumber
        isPrimary:
          type: boolean
          description: Set to true for the faustnumber that currently is the primary object in the work
      required:
        - faust

    CaseSummaryList:
      type: object
      properties:
        numFound:
          type: integer
        cases:
          type: array
          items:
            $ref: '#/components/schemas/CaseSummary'
      required:
        - numFound
        - cases

    CaseSummary:
      type: object
      nullable: true
      properties:
        id:
          type: integer
          description: Case id
        title:
          type: string
          description: Case title (free form, not tied to the bibliographic title of any of the faustnumbers)
        details:
          type: string
          description: Case details (free form)
        primaryFaust:
          type: string
          description: Faustnumber for the primary manifestations, typically one of the paperbooks
        relatedFausts:
          type: array
          items:
            type: string
            description: Other faustnumbers that should link to the review produced by this case
          minItems: 0
        created:
          type: string
          format: date-time
          description: Time of creation
        deadline:
          type: string
          format: date
          nullable: true
          description: Date of delivery
        assigned:
          type: string
          format: date
          nullable: true
          description: Assigned to reviewer on this date
        status:
          $ref: '#/components/schemas/CaseStatus'
        materialType:
          $ref: '#/components/schemas/MaterialType'
      required:
        - id
        - title
        - primaryFaust
        - relatedFausts
        - created
        - status
        - materialType

    Case:
      type: object
      properties:
        id:
          type: integer
          description: Case id
        title:
          type: string
          description: Case title (free form, not tied to the bibliographic title of any of the faustnumbers)
        details:
          type: string
          description: Case details (free form)
        primaryFaust:
          type: string
          description: Faustnumber for the primary manifestations, typically one of the paperbooks
        relatedFausts:
          type: array
          items:
            type: string
          description: Other faustnumbers that should link to the review produced by this case
          minItems: 0
        reviewer:
          $ref: '#/components/schemas/Reviewer'
          nullable: true
          description: The selected reviewer, if any otherwise null
        subjects:
          type: array
          items:
            $ref: '#/components/schemas/Subject'
          minItems: 0
          description: One or more subjects covered by the work to review
        created:
          type: string
          format: date-time
          description: Time of creation
        deadline:
          type: string
          format: date
          nullable: true
          description: Date of delivery
        assigned:
          type: string
          format: date
          nullable: true
          description: Assigned to reviewer on this date
        status:
          $ref: '#/components/schemas/CaseStatus'
        materialType:
          $ref: '#/components/schemas/MaterialType'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
          minItems: 0
      required:
        - id
        - title
        - primaryFaust
        - relatedFausts
        - reviewer
        - subjects
        - created
        - deadline
        - status
        - materialType
        - tasks

    CaseRequest:
      type: object
      properties:
        title:
          type: string
          description: Case title (free form, not tied to the bibliographic title of any of the faustnumbers)
        details:
          type: string
          description: Case details (free form)
          nullable: true
        primaryFaust:
          type: string
          description: Faustnumber for the primary manifestations, typically one of the paperbooks
        relatedFausts:
          type: array
          items:
            type: string
          minItems: 0
          nullable: true
          description: Other faustnumbers that should link to the review produced by this case
        reviewer:
          type: integer
          nullable: true
          description: ID of assigned reviewer
        subjects:
          type: array
          items:
            type: integer
          minItems: 0
          nullable: true
          description: IDs of subjects covered by the work to review
        assigned:
          type: string
          format: date
          nullable: true
          description: Assigned to reviewer on this date
        deadline:
          type: string
          format: date
          nullable: true
          description: Date of delivery
        status:
          $ref: '#/components/schemas/CaseStatus'
        materialType:
          $ref: '#/components/schemas/MaterialType'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
          minItems: 0
          nullable: true
      required:
        - title
        - primaryFaust
        - materialType

    CaseStatus:
      type: string
      nullable: true
      enum:
        - 'CREATED'
        - 'REJECTED'
        - 'ASSIGNED'
        - 'PENDING_APPROVAL'
        - 'PENDING_ISSUES'
        - 'DONE'
        - 'CLOSED'
      description: |
        Enum describing the overall state of this case
        * CREATED = Case has been created but still needs refinement
        * ASSIGNED = Case has been assigned and is in progress
        * REJECTED = Case has been assigned and rejected by the reviewer
        * PENDING_APPROVAL = reviewer has completed all tasks, editor needs to approve
        * PENDING_ISSUES = review could not be approved, further actions needed by the editor and/or reviewer
        * DONE = All tasks is approved and either done or closed
        * CLOSED = Case has been closed, individual task states is undefined

    MaterialType:
      type: string
      enum:
        - 'BOOK'
        - 'MOVIE'
        - 'MULTIMEDIA'

    Task:
      type: object
      properties:
        id:
          type: integer
          description: Task id
        typeOfTask:
          type: string
          enum:
            - 'NONE'  # Todo: define needed task types
          description: Type of task
        created:
          type: string
          format: date
          description: Date of creation
        paycode:
          type: string
          enum:
            - 'NONE'  # Todo: define paycodes
          description: Payment code
        approved:
          type: string
          format: date
          nullable: true
          description: Date of approvement
        payed:
          type: string
          format: date
          nullable: true
          description: Date when first added to a periods payroll. This value must not change hereafter
        data:
          type: string
          description: The task data
          nullable: true
      required:
        - id
        - typeOfTask
        - created
        - paycode
        - approved
        - payed
        - data
